/*
 * generated by Xtext
 */
package mddProject.concreteSyntax.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JDSLUiModule extends mddProject.concreteSyntax.ui.AbstractJDSLUiModule {
	public JDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
