/*
* generated by Xtext
*/

package mddProject.concreteSyntax.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class JDSLGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ContentModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ContentModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cContentModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cContentModelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cNameKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cEqualsSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cNameAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cNameEStringParserRuleCall_5_0 = (RuleCall)cNameAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cContainsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cHasElementsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cHasElementsNamedElementParserRuleCall_6_2_0 = (RuleCall)cHasElementsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cSemicolonKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cHasElementsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cHasElementsNamedElementParserRuleCall_6_3_1_0 = (RuleCall)cHasElementsAssignment_6_3_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6_5 = (Keyword)cGroup_6.eContents().get(5);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//ContentModel:
		//
		//	{ContentModel} "ContentModel" "{" "Name" "=" name=EString ("Contains" "{" hasElements+=NamedElement (";"
		//
		//	hasElements+=NamedElement)* ";" "}")? "}";
		public ParserRule getRule() { return rule; }

		//{ContentModel} "ContentModel" "{" "Name" "=" name=EString ("Contains" "{" hasElements+=NamedElement (";"
		//
		//hasElements+=NamedElement)* ";" "}")? "}"
		public Group getGroup() { return cGroup; }

		//{ContentModel}
		public Action getContentModelAction_0() { return cContentModelAction_0; }

		//"ContentModel"
		public Keyword getContentModelKeyword_1() { return cContentModelKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"Name"
		public Keyword getNameKeyword_3() { return cNameKeyword_3; }

		//"="
		public Keyword getEqualsSignKeyword_4() { return cEqualsSignKeyword_4; }

		//name=EString
		public Assignment getNameAssignment_5() { return cNameAssignment_5; }

		//EString
		public RuleCall getNameEStringParserRuleCall_5_0() { return cNameEStringParserRuleCall_5_0; }

		//("Contains" "{" hasElements+=NamedElement (";" hasElements+=NamedElement)* ";" "}")?
		public Group getGroup_6() { return cGroup_6; }

		//"Contains"
		public Keyword getContainsKeyword_6_0() { return cContainsKeyword_6_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }

		//hasElements+=NamedElement
		public Assignment getHasElementsAssignment_6_2() { return cHasElementsAssignment_6_2; }

		//NamedElement
		public RuleCall getHasElementsNamedElementParserRuleCall_6_2_0() { return cHasElementsNamedElementParserRuleCall_6_2_0; }

		//(";" hasElements+=NamedElement)*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//";"
		public Keyword getSemicolonKeyword_6_3_0() { return cSemicolonKeyword_6_3_0; }

		//hasElements+=NamedElement
		public Assignment getHasElementsAssignment_6_3_1() { return cHasElementsAssignment_6_3_1; }

		//NamedElement
		public RuleCall getHasElementsNamedElementParserRuleCall_6_3_1_0() { return cHasElementsNamedElementParserRuleCall_6_3_1_0; }

		//";"
		public Keyword getSemicolonKeyword_6_4() { return cSemicolonKeyword_6_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6_5() { return cRightCurlyBracketKeyword_6_5; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class NamedElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "NamedElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cContentTypeParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCMSParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//NamedElement:
		//
		//	ContentType | CMS;
		public ParserRule getRule() { return rule; }

		//ContentType | CMS
		public Alternatives getAlternatives() { return cAlternatives; }

		//ContentType
		public RuleCall getContentTypeParserRuleCall_0() { return cContentTypeParserRuleCall_0; }

		//CMS
		public RuleCall getCMSParserRuleCall_1() { return cCMSParserRuleCall_1; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class ContentTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ContentType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cVisibleAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cVisibleVisibleKeyword_0_0 = (Keyword)cVisibleAssignment_0.eContents().get(0);
		private final Keyword cContentTypeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cNameKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cEqualsSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cNameAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cNameEStringParserRuleCall_5_0 = (RuleCall)cNameAssignment_5.eContents().get(0);
		private final Keyword cPropertiesKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cLeftCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cHasPropertiesAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cHasPropertiesPropertyParserRuleCall_8_0 = (RuleCall)cHasPropertiesAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cSemicolonKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cHasPropertiesAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cHasPropertiesPropertyParserRuleCall_9_1_0 = (RuleCall)cHasPropertiesAssignment_9_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cGuidKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Keyword cEqualsSignKeyword_12_1 = (Keyword)cGroup_12.eContents().get(1);
		private final Assignment cGuidAssignment_12_2 = (Assignment)cGroup_12.eContents().get(2);
		private final RuleCall cGuidEIntParserRuleCall_12_2_0 = (RuleCall)cGuidAssignment_12_2.eContents().get(0);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cVersionsKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_13_1 = (Keyword)cGroup_13.eContents().get(1);
		private final Assignment cHasVersionsAssignment_13_2 = (Assignment)cGroup_13.eContents().get(2);
		private final RuleCall cHasVersionsVersionParserRuleCall_13_2_0 = (RuleCall)cHasVersionsAssignment_13_2.eContents().get(0);
		private final Group cGroup_13_3 = (Group)cGroup_13.eContents().get(3);
		private final Keyword cSemicolonKeyword_13_3_0 = (Keyword)cGroup_13_3.eContents().get(0);
		private final Assignment cHasVersionsAssignment_13_3_1 = (Assignment)cGroup_13_3.eContents().get(1);
		private final RuleCall cHasVersionsVersionParserRuleCall_13_3_1_0 = (RuleCall)cHasVersionsAssignment_13_3_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_13_4 = (Keyword)cGroup_13.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_13_5 = (Keyword)cGroup_13.eContents().get(5);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cModifiedByKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Keyword cEqualsSignKeyword_14_1 = (Keyword)cGroup_14.eContents().get(1);
		private final Assignment cModifiedByAssignment_14_2 = (Assignment)cGroup_14.eContents().get(2);
		private final RuleCall cModifiedByUserParserRuleCall_14_2_0 = (RuleCall)cModifiedByAssignment_14_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		
		//ContentType:
		//
		//	visible?="visible"? "ContentType" "{" "Name" "=" name=EString "Properties" "{" hasProperties+=Property (";"
		//
		//	hasProperties+=Property)* ";" "}" ("Guid" "=" guid=EInt)? ("Versions" "{" hasVersions+=Version (";"
		//
		//	hasVersions+=Version)* ";" "}")? ("ModifiedBy" "=" modifiedBy=User)? "}";
		public ParserRule getRule() { return rule; }

		//visible?="visible"? "ContentType" "{" "Name" "=" name=EString "Properties" "{" hasProperties+=Property (";"
		//
		//hasProperties+=Property)* ";" "}" ("Guid" "=" guid=EInt)? ("Versions" "{" hasVersions+=Version (";"
		//
		//hasVersions+=Version)* ";" "}")? ("ModifiedBy" "=" modifiedBy=User)? "}"
		public Group getGroup() { return cGroup; }

		//visible?="visible"?
		public Assignment getVisibleAssignment_0() { return cVisibleAssignment_0; }

		//"visible"
		public Keyword getVisibleVisibleKeyword_0_0() { return cVisibleVisibleKeyword_0_0; }

		//"ContentType"
		public Keyword getContentTypeKeyword_1() { return cContentTypeKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"Name"
		public Keyword getNameKeyword_3() { return cNameKeyword_3; }

		//"="
		public Keyword getEqualsSignKeyword_4() { return cEqualsSignKeyword_4; }

		//name=EString
		public Assignment getNameAssignment_5() { return cNameAssignment_5; }

		//EString
		public RuleCall getNameEStringParserRuleCall_5_0() { return cNameEStringParserRuleCall_5_0; }

		//"Properties"
		public Keyword getPropertiesKeyword_6() { return cPropertiesKeyword_6; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_7() { return cLeftCurlyBracketKeyword_7; }

		//hasProperties+=Property
		public Assignment getHasPropertiesAssignment_8() { return cHasPropertiesAssignment_8; }

		//Property
		public RuleCall getHasPropertiesPropertyParserRuleCall_8_0() { return cHasPropertiesPropertyParserRuleCall_8_0; }

		//(";" hasProperties+=Property)*
		public Group getGroup_9() { return cGroup_9; }

		//";"
		public Keyword getSemicolonKeyword_9_0() { return cSemicolonKeyword_9_0; }

		//hasProperties+=Property
		public Assignment getHasPropertiesAssignment_9_1() { return cHasPropertiesAssignment_9_1; }

		//Property
		public RuleCall getHasPropertiesPropertyParserRuleCall_9_1_0() { return cHasPropertiesPropertyParserRuleCall_9_1_0; }

		//";"
		public Keyword getSemicolonKeyword_10() { return cSemicolonKeyword_10; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }

		//("Guid" "=" guid=EInt)?
		public Group getGroup_12() { return cGroup_12; }

		//"Guid"
		public Keyword getGuidKeyword_12_0() { return cGuidKeyword_12_0; }

		//"="
		public Keyword getEqualsSignKeyword_12_1() { return cEqualsSignKeyword_12_1; }

		//guid=EInt
		public Assignment getGuidAssignment_12_2() { return cGuidAssignment_12_2; }

		//EInt
		public RuleCall getGuidEIntParserRuleCall_12_2_0() { return cGuidEIntParserRuleCall_12_2_0; }

		//("Versions" "{" hasVersions+=Version (";" hasVersions+=Version)* ";" "}")?
		public Group getGroup_13() { return cGroup_13; }

		//"Versions"
		public Keyword getVersionsKeyword_13_0() { return cVersionsKeyword_13_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_13_1() { return cLeftCurlyBracketKeyword_13_1; }

		//hasVersions+=Version
		public Assignment getHasVersionsAssignment_13_2() { return cHasVersionsAssignment_13_2; }

		//Version
		public RuleCall getHasVersionsVersionParserRuleCall_13_2_0() { return cHasVersionsVersionParserRuleCall_13_2_0; }

		//(";" hasVersions+=Version)*
		public Group getGroup_13_3() { return cGroup_13_3; }

		//";"
		public Keyword getSemicolonKeyword_13_3_0() { return cSemicolonKeyword_13_3_0; }

		//hasVersions+=Version
		public Assignment getHasVersionsAssignment_13_3_1() { return cHasVersionsAssignment_13_3_1; }

		//Version
		public RuleCall getHasVersionsVersionParserRuleCall_13_3_1_0() { return cHasVersionsVersionParserRuleCall_13_3_1_0; }

		//";"
		public Keyword getSemicolonKeyword_13_4() { return cSemicolonKeyword_13_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_13_5() { return cRightCurlyBracketKeyword_13_5; }

		//("ModifiedBy" "=" modifiedBy=User)?
		public Group getGroup_14() { return cGroup_14; }

		//"ModifiedBy"
		public Keyword getModifiedByKeyword_14_0() { return cModifiedByKeyword_14_0; }

		//"="
		public Keyword getEqualsSignKeyword_14_1() { return cEqualsSignKeyword_14_1; }

		//modifiedBy=User
		public Assignment getModifiedByAssignment_14_2() { return cModifiedByAssignment_14_2; }

		//User
		public RuleCall getModifiedByUserParserRuleCall_14_2_0() { return cModifiedByUserParserRuleCall_14_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_15() { return cRightCurlyBracketKeyword_15; }
	}

	public class PropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Property");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPropertyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameEStringParserRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Keyword cAccessModifierKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cEqualsSignKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cAccessModiferAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cAccessModiferAccessLevelEnumEnumRuleCall_7_0 = (RuleCall)cAccessModiferAssignment_7.eContents().get(0);
		private final Keyword cTypeKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cEqualsSignKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cTypeAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cTypeTypeEnumEnumRuleCall_10_0 = (RuleCall)cTypeAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Property:
		//
		//	"Property" "{" "Name" "=" name=EString "AccessModifier" "=" accessModifer=AccessLevelEnum "Type" "=" type=TypeEnum
		//
		//	"}";
		public ParserRule getRule() { return rule; }

		//"Property" "{" "Name" "=" name=EString "AccessModifier" "=" accessModifer=AccessLevelEnum "Type" "=" type=TypeEnum "}"
		public Group getGroup() { return cGroup; }

		//"Property"
		public Keyword getPropertyKeyword_0() { return cPropertyKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"Name"
		public Keyword getNameKeyword_2() { return cNameKeyword_2; }

		//"="
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }

		//name=EString
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }

		//EString
		public RuleCall getNameEStringParserRuleCall_4_0() { return cNameEStringParserRuleCall_4_0; }

		//"AccessModifier"
		public Keyword getAccessModifierKeyword_5() { return cAccessModifierKeyword_5; }

		//"="
		public Keyword getEqualsSignKeyword_6() { return cEqualsSignKeyword_6; }

		//accessModifer=AccessLevelEnum
		public Assignment getAccessModiferAssignment_7() { return cAccessModiferAssignment_7; }

		//AccessLevelEnum
		public RuleCall getAccessModiferAccessLevelEnumEnumRuleCall_7_0() { return cAccessModiferAccessLevelEnumEnumRuleCall_7_0; }

		//"Type"
		public Keyword getTypeKeyword_8() { return cTypeKeyword_8; }

		//"="
		public Keyword getEqualsSignKeyword_9() { return cEqualsSignKeyword_9; }

		//type=TypeEnum
		public Assignment getTypeAssignment_10() { return cTypeAssignment_10; }

		//TypeEnum
		public RuleCall getTypeTypeEnumEnumRuleCall_10_0() { return cTypeTypeEnumEnumRuleCall_10_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}

	public class RoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Role");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRoleAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cIsAdminAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cIsAdminIsAdminKeyword_1_0 = (Keyword)cIsAdminAssignment_1.eContents().get(0);
		private final Keyword cRoleKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cEqualsSignKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cNameAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cNameEStringParserRuleCall_6_0 = (RuleCall)cNameAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cTypesKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cTypesAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cTypesEStringParserRuleCall_7_2_0 = (RuleCall)cTypesAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cSemicolonKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cTypesAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cTypesEStringParserRuleCall_7_3_1_0 = (RuleCall)cTypesAssignment_7_3_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7_5 = (Keyword)cGroup_7.eContents().get(5);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Role:
		//
		//	{Role} isAdmin?="isAdmin"? "Role" "{" "Name" "=" name=EString ("Types" "{" types+=EString (";" types+=EString)* ";"
		//
		//	"}")? "}";
		public ParserRule getRule() { return rule; }

		//{Role} isAdmin?="isAdmin"? "Role" "{" "Name" "=" name=EString ("Types" "{" types+=EString (";" types+=EString)* ";"
		//
		//"}")? "}"
		public Group getGroup() { return cGroup; }

		//{Role}
		public Action getRoleAction_0() { return cRoleAction_0; }

		//isAdmin?="isAdmin"?
		public Assignment getIsAdminAssignment_1() { return cIsAdminAssignment_1; }

		//"isAdmin"
		public Keyword getIsAdminIsAdminKeyword_1_0() { return cIsAdminIsAdminKeyword_1_0; }

		//"Role"
		public Keyword getRoleKeyword_2() { return cRoleKeyword_2; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//"Name"
		public Keyword getNameKeyword_4() { return cNameKeyword_4; }

		//"="
		public Keyword getEqualsSignKeyword_5() { return cEqualsSignKeyword_5; }

		//name=EString
		public Assignment getNameAssignment_6() { return cNameAssignment_6; }

		//EString
		public RuleCall getNameEStringParserRuleCall_6_0() { return cNameEStringParserRuleCall_6_0; }

		//("Types" "{" types+=EString (";" types+=EString)* ";" "}")?
		public Group getGroup_7() { return cGroup_7; }

		//"Types"
		public Keyword getTypesKeyword_7_0() { return cTypesKeyword_7_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }

		//types+=EString
		public Assignment getTypesAssignment_7_2() { return cTypesAssignment_7_2; }

		//EString
		public RuleCall getTypesEStringParserRuleCall_7_2_0() { return cTypesEStringParserRuleCall_7_2_0; }

		//(";" types+=EString)*
		public Group getGroup_7_3() { return cGroup_7_3; }

		//";"
		public Keyword getSemicolonKeyword_7_3_0() { return cSemicolonKeyword_7_3_0; }

		//types+=EString
		public Assignment getTypesAssignment_7_3_1() { return cTypesAssignment_7_3_1; }

		//EString
		public RuleCall getTypesEStringParserRuleCall_7_3_1_0() { return cTypesEStringParserRuleCall_7_3_1_0; }

		//";"
		public Keyword getSemicolonKeyword_7_4() { return cSemicolonKeyword_7_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7_5() { return cRightCurlyBracketKeyword_7_5; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class UserElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "User");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cUserAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cDisabledAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cDisabledDisabledKeyword_1_0 = (Keyword)cDisabledAssignment_1.eContents().get(0);
		private final Keyword cUserKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cEqualsSignKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cNameAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cNameEStringParserRuleCall_6_0 = (RuleCall)cNameAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cUserFirstNameKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cEqualsSignKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cFirstnameAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cFirstnameEStringParserRuleCall_7_2_0 = (RuleCall)cFirstnameAssignment_7_2.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cUserLastNameKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cEqualsSignKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cLastnameAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cLastnameEStringParserRuleCall_8_2_0 = (RuleCall)cLastnameAssignment_8_2.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cLoginKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cEqualsSignKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cLoginAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cLoginEStringParserRuleCall_9_2_0 = (RuleCall)cLoginAssignment_9_2.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cPasswordKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cEqualsSignKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Assignment cPasswordAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final RuleCall cPasswordEStringParserRuleCall_10_2_0 = (RuleCall)cPasswordAssignment_10_2.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cEmailKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Keyword cEqualsSignKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Assignment cEmailAssignment_11_2 = (Assignment)cGroup_11.eContents().get(2);
		private final RuleCall cEmailEStringParserRuleCall_11_2_0 = (RuleCall)cEmailAssignment_11_2.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cRoleKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Keyword cEqualsSignKeyword_12_1 = (Keyword)cGroup_12.eContents().get(1);
		private final Assignment cHasRoleAssignment_12_2 = (Assignment)cGroup_12.eContents().get(2);
		private final RuleCall cHasRoleRoleParserRuleCall_12_2_0 = (RuleCall)cHasRoleAssignment_12_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//User:
		//
		//	{User} disabled?="disabled"? "User" "{" "Name" "=" name=EString ("userFirstName" "=" firstname=EString)?
		//
		//	("userLastName" "=" lastname=EString)? ("Login" "=" login=EString)? ("Password" "=" password=EString)? ("Email" "="
		//
		//	email=EString)? ("Role" "=" hasRole=Role)? "}";
		public ParserRule getRule() { return rule; }

		//{User} disabled?="disabled"? "User" "{" "Name" "=" name=EString ("userFirstName" "=" firstname=EString)? ("userLastName"
		//
		//"=" lastname=EString)? ("Login" "=" login=EString)? ("Password" "=" password=EString)? ("Email" "=" email=EString)?
		//
		//("Role" "=" hasRole=Role)? "}"
		public Group getGroup() { return cGroup; }

		//{User}
		public Action getUserAction_0() { return cUserAction_0; }

		//disabled?="disabled"?
		public Assignment getDisabledAssignment_1() { return cDisabledAssignment_1; }

		//"disabled"
		public Keyword getDisabledDisabledKeyword_1_0() { return cDisabledDisabledKeyword_1_0; }

		//"User"
		public Keyword getUserKeyword_2() { return cUserKeyword_2; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//"Name"
		public Keyword getNameKeyword_4() { return cNameKeyword_4; }

		//"="
		public Keyword getEqualsSignKeyword_5() { return cEqualsSignKeyword_5; }

		//name=EString
		public Assignment getNameAssignment_6() { return cNameAssignment_6; }

		//EString
		public RuleCall getNameEStringParserRuleCall_6_0() { return cNameEStringParserRuleCall_6_0; }

		//("userFirstName" "=" firstname=EString)?
		public Group getGroup_7() { return cGroup_7; }

		//"userFirstName"
		public Keyword getUserFirstNameKeyword_7_0() { return cUserFirstNameKeyword_7_0; }

		//"="
		public Keyword getEqualsSignKeyword_7_1() { return cEqualsSignKeyword_7_1; }

		//firstname=EString
		public Assignment getFirstnameAssignment_7_2() { return cFirstnameAssignment_7_2; }

		//EString
		public RuleCall getFirstnameEStringParserRuleCall_7_2_0() { return cFirstnameEStringParserRuleCall_7_2_0; }

		//("userLastName" "=" lastname=EString)?
		public Group getGroup_8() { return cGroup_8; }

		//"userLastName"
		public Keyword getUserLastNameKeyword_8_0() { return cUserLastNameKeyword_8_0; }

		//"="
		public Keyword getEqualsSignKeyword_8_1() { return cEqualsSignKeyword_8_1; }

		//lastname=EString
		public Assignment getLastnameAssignment_8_2() { return cLastnameAssignment_8_2; }

		//EString
		public RuleCall getLastnameEStringParserRuleCall_8_2_0() { return cLastnameEStringParserRuleCall_8_2_0; }

		//("Login" "=" login=EString)?
		public Group getGroup_9() { return cGroup_9; }

		//"Login"
		public Keyword getLoginKeyword_9_0() { return cLoginKeyword_9_0; }

		//"="
		public Keyword getEqualsSignKeyword_9_1() { return cEqualsSignKeyword_9_1; }

		//login=EString
		public Assignment getLoginAssignment_9_2() { return cLoginAssignment_9_2; }

		//EString
		public RuleCall getLoginEStringParserRuleCall_9_2_0() { return cLoginEStringParserRuleCall_9_2_0; }

		//("Password" "=" password=EString)?
		public Group getGroup_10() { return cGroup_10; }

		//"Password"
		public Keyword getPasswordKeyword_10_0() { return cPasswordKeyword_10_0; }

		//"="
		public Keyword getEqualsSignKeyword_10_1() { return cEqualsSignKeyword_10_1; }

		//password=EString
		public Assignment getPasswordAssignment_10_2() { return cPasswordAssignment_10_2; }

		//EString
		public RuleCall getPasswordEStringParserRuleCall_10_2_0() { return cPasswordEStringParserRuleCall_10_2_0; }

		//("Email" "=" email=EString)?
		public Group getGroup_11() { return cGroup_11; }

		//"Email"
		public Keyword getEmailKeyword_11_0() { return cEmailKeyword_11_0; }

		//"="
		public Keyword getEqualsSignKeyword_11_1() { return cEqualsSignKeyword_11_1; }

		//email=EString
		public Assignment getEmailAssignment_11_2() { return cEmailAssignment_11_2; }

		//EString
		public RuleCall getEmailEStringParserRuleCall_11_2_0() { return cEmailEStringParserRuleCall_11_2_0; }

		//("Role" "=" hasRole=Role)?
		public Group getGroup_12() { return cGroup_12; }

		//"Role"
		public Keyword getRoleKeyword_12_0() { return cRoleKeyword_12_0; }

		//"="
		public Keyword getEqualsSignKeyword_12_1() { return cEqualsSignKeyword_12_1; }

		//hasRole=Role
		public Assignment getHasRoleAssignment_12_2() { return cHasRoleAssignment_12_2; }

		//Role
		public RuleCall getHasRoleRoleParserRuleCall_12_2_0() { return cHasRoleRoleParserRuleCall_12_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}

	public class VersionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Version");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVersionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cVersionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cNumberKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameEStringParserRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		
		//Version:
		//
		//	{Version} "Version" "Number" "=" name=EString;
		public ParserRule getRule() { return rule; }

		//{Version} "Version" "Number" "=" name=EString
		public Group getGroup() { return cGroup; }

		//{Version}
		public Action getVersionAction_0() { return cVersionAction_0; }

		//"Version"
		public Keyword getVersionKeyword_1() { return cVersionKeyword_1; }

		//"Number"
		public Keyword getNumberKeyword_2() { return cNumberKeyword_2; }

		//"="
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }

		//name=EString
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }

		//EString
		public RuleCall getNameEStringParserRuleCall_4_0() { return cNameEStringParserRuleCall_4_0; }
	}

	public class CMSElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CMS");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCMSAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCMSKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cNameKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cEqualsSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cNameAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cNameEStringParserRuleCall_5_0 = (RuleCall)cNameAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cTypeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cEqualsSignKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cTypeAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cTypeCMSEnumEnumRuleCall_6_2_0 = (RuleCall)cTypeAssignment_6_2.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cAddress_urlKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cEqualsSignKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cAddress_urlAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cAddress_urlEStringParserRuleCall_7_2_0 = (RuleCall)cAddress_urlAssignment_7_2.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cUsernameKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cEqualsSignKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cUsernameAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cUsernameEStringParserRuleCall_8_2_0 = (RuleCall)cUsernameAssignment_8_2.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cPasswordKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cEqualsSignKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cPasswordAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cPasswordEStringParserRuleCall_9_2_0 = (RuleCall)cPasswordAssignment_9_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//CMS:
		//
		//	{CMS} "CMS" "{" "Name" "=" name=EString ("Type" "=" type=CMSEnum) ("Address_url" "=" address_url=EString) ("Username"
		//
		//	"=" username=EString) ("Password" "=" password=EString) "}";
		public ParserRule getRule() { return rule; }

		//{CMS} "CMS" "{" "Name" "=" name=EString ("Type" "=" type=CMSEnum) ("Address_url" "=" address_url=EString) ("Username"
		//
		//"=" username=EString) ("Password" "=" password=EString) "}"
		public Group getGroup() { return cGroup; }

		//{CMS}
		public Action getCMSAction_0() { return cCMSAction_0; }

		//"CMS"
		public Keyword getCMSKeyword_1() { return cCMSKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"Name"
		public Keyword getNameKeyword_3() { return cNameKeyword_3; }

		//"="
		public Keyword getEqualsSignKeyword_4() { return cEqualsSignKeyword_4; }

		//name=EString
		public Assignment getNameAssignment_5() { return cNameAssignment_5; }

		//EString
		public RuleCall getNameEStringParserRuleCall_5_0() { return cNameEStringParserRuleCall_5_0; }

		//"Type" "=" type=CMSEnum
		public Group getGroup_6() { return cGroup_6; }

		//"Type"
		public Keyword getTypeKeyword_6_0() { return cTypeKeyword_6_0; }

		//"="
		public Keyword getEqualsSignKeyword_6_1() { return cEqualsSignKeyword_6_1; }

		//type=CMSEnum
		public Assignment getTypeAssignment_6_2() { return cTypeAssignment_6_2; }

		//CMSEnum
		public RuleCall getTypeCMSEnumEnumRuleCall_6_2_0() { return cTypeCMSEnumEnumRuleCall_6_2_0; }

		//"Address_url" "=" address_url=EString
		public Group getGroup_7() { return cGroup_7; }

		//"Address_url"
		public Keyword getAddress_urlKeyword_7_0() { return cAddress_urlKeyword_7_0; }

		//"="
		public Keyword getEqualsSignKeyword_7_1() { return cEqualsSignKeyword_7_1; }

		//address_url=EString
		public Assignment getAddress_urlAssignment_7_2() { return cAddress_urlAssignment_7_2; }

		//EString
		public RuleCall getAddress_urlEStringParserRuleCall_7_2_0() { return cAddress_urlEStringParserRuleCall_7_2_0; }

		//"Username" "=" username=EString
		public Group getGroup_8() { return cGroup_8; }

		//"Username"
		public Keyword getUsernameKeyword_8_0() { return cUsernameKeyword_8_0; }

		//"="
		public Keyword getEqualsSignKeyword_8_1() { return cEqualsSignKeyword_8_1; }

		//username=EString
		public Assignment getUsernameAssignment_8_2() { return cUsernameAssignment_8_2; }

		//EString
		public RuleCall getUsernameEStringParserRuleCall_8_2_0() { return cUsernameEStringParserRuleCall_8_2_0; }

		//"Password" "=" password=EString
		public Group getGroup_9() { return cGroup_9; }

		//"Password"
		public Keyword getPasswordKeyword_9_0() { return cPasswordKeyword_9_0; }

		//"="
		public Keyword getEqualsSignKeyword_9_1() { return cEqualsSignKeyword_9_1; }

		//password=EString
		public Assignment getPasswordAssignment_9_2() { return cPasswordAssignment_9_2; }

		//EString
		public RuleCall getPasswordEStringParserRuleCall_9_2_0() { return cPasswordEStringParserRuleCall_9_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}

	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//
		//	"-"? INT;
		public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//
		//	"true" | "false";
		public ParserRule getRule() { return rule; }

		//"true" | "false"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"true"
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }

		//"false"
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	
	
	public class TypeEnumElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "TypeEnum");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCharEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCharCharKeyword_0_0 = (Keyword)cCharEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cByteEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cByteByteKeyword_1_0 = (Keyword)cByteEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cStringEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cStringStringKeyword_2_0 = (Keyword)cStringEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cIntEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cIntIntKeyword_3_0 = (Keyword)cIntEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cFloatEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cFloatFloatKeyword_4_0 = (Keyword)cFloatEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cDoubleEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cDoubleDoubleKeyword_5_0 = (Keyword)cDoubleEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cBooleanEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cBooleanBooleanKeyword_6_0 = (Keyword)cBooleanEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cDateEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cDateDateKeyword_7_0 = (Keyword)cDateEnumLiteralDeclaration_7.eContents().get(0);
		
		//enum TypeEnum:
		//
		//	char | byte | string | int | float | double | boolean | date;
		public EnumRule getRule() { return rule; }

		//char | byte | string | int | float | double | boolean | date
		public Alternatives getAlternatives() { return cAlternatives; }

		//char
		public EnumLiteralDeclaration getCharEnumLiteralDeclaration_0() { return cCharEnumLiteralDeclaration_0; }

		//"char"
		public Keyword getCharCharKeyword_0_0() { return cCharCharKeyword_0_0; }

		//byte
		public EnumLiteralDeclaration getByteEnumLiteralDeclaration_1() { return cByteEnumLiteralDeclaration_1; }

		//"byte"
		public Keyword getByteByteKeyword_1_0() { return cByteByteKeyword_1_0; }

		//string
		public EnumLiteralDeclaration getStringEnumLiteralDeclaration_2() { return cStringEnumLiteralDeclaration_2; }

		//"string"
		public Keyword getStringStringKeyword_2_0() { return cStringStringKeyword_2_0; }

		//int
		public EnumLiteralDeclaration getIntEnumLiteralDeclaration_3() { return cIntEnumLiteralDeclaration_3; }

		//"int"
		public Keyword getIntIntKeyword_3_0() { return cIntIntKeyword_3_0; }

		//float
		public EnumLiteralDeclaration getFloatEnumLiteralDeclaration_4() { return cFloatEnumLiteralDeclaration_4; }

		//"float"
		public Keyword getFloatFloatKeyword_4_0() { return cFloatFloatKeyword_4_0; }

		//double
		public EnumLiteralDeclaration getDoubleEnumLiteralDeclaration_5() { return cDoubleEnumLiteralDeclaration_5; }

		//"double"
		public Keyword getDoubleDoubleKeyword_5_0() { return cDoubleDoubleKeyword_5_0; }

		//boolean
		public EnumLiteralDeclaration getBooleanEnumLiteralDeclaration_6() { return cBooleanEnumLiteralDeclaration_6; }

		//"boolean"
		public Keyword getBooleanBooleanKeyword_6_0() { return cBooleanBooleanKeyword_6_0; }

		//date
		public EnumLiteralDeclaration getDateEnumLiteralDeclaration_7() { return cDateEnumLiteralDeclaration_7; }

		//"date"
		public Keyword getDateDateKeyword_7_0() { return cDateDateKeyword_7_0; }
	}

	public class CMSEnumElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "CMSEnum");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cJeaseEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cJeaseJeaseKeyword_0_0 = (Keyword)cJeaseEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cN2EnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cN2N2Keyword_1_0 = (Keyword)cN2EnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cConcrete5EnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cConcrete5Concrete5Keyword_2_0 = (Keyword)cConcrete5EnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cPloneEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cPlonePloneKeyword_3_0 = (Keyword)cPloneEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum CMSEnum:
		//
		//	Jease | N2 | Concrete5 | Plone;
		public EnumRule getRule() { return rule; }

		//Jease | N2 | Concrete5 | Plone
		public Alternatives getAlternatives() { return cAlternatives; }

		//Jease
		public EnumLiteralDeclaration getJeaseEnumLiteralDeclaration_0() { return cJeaseEnumLiteralDeclaration_0; }

		//"Jease"
		public Keyword getJeaseJeaseKeyword_0_0() { return cJeaseJeaseKeyword_0_0; }

		//N2
		public EnumLiteralDeclaration getN2EnumLiteralDeclaration_1() { return cN2EnumLiteralDeclaration_1; }

		//"N2"
		public Keyword getN2N2Keyword_1_0() { return cN2N2Keyword_1_0; }

		//Concrete5
		public EnumLiteralDeclaration getConcrete5EnumLiteralDeclaration_2() { return cConcrete5EnumLiteralDeclaration_2; }

		//"Concrete5"
		public Keyword getConcrete5Concrete5Keyword_2_0() { return cConcrete5Concrete5Keyword_2_0; }

		//Plone
		public EnumLiteralDeclaration getPloneEnumLiteralDeclaration_3() { return cPloneEnumLiteralDeclaration_3; }

		//"Plone"
		public Keyword getPlonePloneKeyword_3_0() { return cPlonePloneKeyword_3_0; }
	}

	public class AccessLevelEnumElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "AccessLevelEnum");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPublicEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPublicPublicKeyword_0_0 = (Keyword)cPublicEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPrivateEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPrivatePrivateKeyword_1_0 = (Keyword)cPrivateEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum AccessLevelEnum:
		//
		//	public | private;
		public EnumRule getRule() { return rule; }

		//public | private
		public Alternatives getAlternatives() { return cAlternatives; }

		//public
		public EnumLiteralDeclaration getPublicEnumLiteralDeclaration_0() { return cPublicEnumLiteralDeclaration_0; }

		//"public"
		public Keyword getPublicPublicKeyword_0_0() { return cPublicPublicKeyword_0_0; }

		//private
		public EnumLiteralDeclaration getPrivateEnumLiteralDeclaration_1() { return cPrivateEnumLiteralDeclaration_1; }

		//"private"
		public Keyword getPrivatePrivateKeyword_1_0() { return cPrivatePrivateKeyword_1_0; }
	}
	
	private ContentModelElements pContentModel;
	private NamedElementElements pNamedElement;
	private EStringElements pEString;
	private ContentTypeElements pContentType;
	private PropertyElements pProperty;
	private RoleElements pRole;
	private UserElements pUser;
	private VersionElements pVersion;
	private CMSElements pCMS;
	private EIntElements pEInt;
	private EBooleanElements pEBoolean;
	private TypeEnumElements unknownRuleTypeEnum;
	private CMSEnumElements unknownRuleCMSEnum;
	private AccessLevelEnumElements unknownRuleAccessLevelEnum;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public JDSLGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("mddProject.concreteSyntax.JDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//ContentModel:
	//
	//	{ContentModel} "ContentModel" "{" "Name" "=" name=EString ("Contains" "{" hasElements+=NamedElement (";"
	//
	//	hasElements+=NamedElement)* ";" "}")? "}";
	public ContentModelElements getContentModelAccess() {
		return (pContentModel != null) ? pContentModel : (pContentModel = new ContentModelElements());
	}
	
	public ParserRule getContentModelRule() {
		return getContentModelAccess().getRule();
	}

	//NamedElement:
	//
	//	ContentType | CMS;
	public NamedElementElements getNamedElementAccess() {
		return (pNamedElement != null) ? pNamedElement : (pNamedElement = new NamedElementElements());
	}
	
	public ParserRule getNamedElementRule() {
		return getNamedElementAccess().getRule();
	}

	//EString returns ecore::EString:
	//
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return (pEString != null) ? pEString : (pEString = new EStringElements());
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//ContentType:
	//
	//	visible?="visible"? "ContentType" "{" "Name" "=" name=EString "Properties" "{" hasProperties+=Property (";"
	//
	//	hasProperties+=Property)* ";" "}" ("Guid" "=" guid=EInt)? ("Versions" "{" hasVersions+=Version (";"
	//
	//	hasVersions+=Version)* ";" "}")? ("ModifiedBy" "=" modifiedBy=User)? "}";
	public ContentTypeElements getContentTypeAccess() {
		return (pContentType != null) ? pContentType : (pContentType = new ContentTypeElements());
	}
	
	public ParserRule getContentTypeRule() {
		return getContentTypeAccess().getRule();
	}

	//Property:
	//
	//	"Property" "{" "Name" "=" name=EString "AccessModifier" "=" accessModifer=AccessLevelEnum "Type" "=" type=TypeEnum
	//
	//	"}";
	public PropertyElements getPropertyAccess() {
		return (pProperty != null) ? pProperty : (pProperty = new PropertyElements());
	}
	
	public ParserRule getPropertyRule() {
		return getPropertyAccess().getRule();
	}

	//Role:
	//
	//	{Role} isAdmin?="isAdmin"? "Role" "{" "Name" "=" name=EString ("Types" "{" types+=EString (";" types+=EString)* ";"
	//
	//	"}")? "}";
	public RoleElements getRoleAccess() {
		return (pRole != null) ? pRole : (pRole = new RoleElements());
	}
	
	public ParserRule getRoleRule() {
		return getRoleAccess().getRule();
	}

	//User:
	//
	//	{User} disabled?="disabled"? "User" "{" "Name" "=" name=EString ("userFirstName" "=" firstname=EString)?
	//
	//	("userLastName" "=" lastname=EString)? ("Login" "=" login=EString)? ("Password" "=" password=EString)? ("Email" "="
	//
	//	email=EString)? ("Role" "=" hasRole=Role)? "}";
	public UserElements getUserAccess() {
		return (pUser != null) ? pUser : (pUser = new UserElements());
	}
	
	public ParserRule getUserRule() {
		return getUserAccess().getRule();
	}

	//Version:
	//
	//	{Version} "Version" "Number" "=" name=EString;
	public VersionElements getVersionAccess() {
		return (pVersion != null) ? pVersion : (pVersion = new VersionElements());
	}
	
	public ParserRule getVersionRule() {
		return getVersionAccess().getRule();
	}

	//CMS:
	//
	//	{CMS} "CMS" "{" "Name" "=" name=EString ("Type" "=" type=CMSEnum) ("Address_url" "=" address_url=EString) ("Username"
	//
	//	"=" username=EString) ("Password" "=" password=EString) "}";
	public CMSElements getCMSAccess() {
		return (pCMS != null) ? pCMS : (pCMS = new CMSElements());
	}
	
	public ParserRule getCMSRule() {
		return getCMSAccess().getRule();
	}

	//EInt returns ecore::EInt:
	//
	//	"-"? INT;
	public EIntElements getEIntAccess() {
		return (pEInt != null) ? pEInt : (pEInt = new EIntElements());
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//EBoolean returns ecore::EBoolean:
	//
	//	"true" | "false";
	public EBooleanElements getEBooleanAccess() {
		return (pEBoolean != null) ? pEBoolean : (pEBoolean = new EBooleanElements());
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}

	//enum TypeEnum:
	//
	//	char | byte | string | int | float | double | boolean | date;
	public TypeEnumElements getTypeEnumAccess() {
		return (unknownRuleTypeEnum != null) ? unknownRuleTypeEnum : (unknownRuleTypeEnum = new TypeEnumElements());
	}
	
	public EnumRule getTypeEnumRule() {
		return getTypeEnumAccess().getRule();
	}

	//enum CMSEnum:
	//
	//	Jease | N2 | Concrete5 | Plone;
	public CMSEnumElements getCMSEnumAccess() {
		return (unknownRuleCMSEnum != null) ? unknownRuleCMSEnum : (unknownRuleCMSEnum = new CMSEnumElements());
	}
	
	public EnumRule getCMSEnumRule() {
		return getCMSEnumAccess().getRule();
	}

	//enum AccessLevelEnum:
	//
	//	public | private;
	public AccessLevelEnumElements getAccessLevelEnumAccess() {
		return (unknownRuleAccessLevelEnum != null) ? unknownRuleAccessLevelEnum : (unknownRuleAccessLevelEnum = new AccessLevelEnumElements());
	}
	
	public EnumRule getAccessLevelEnumRule() {
		return getAccessLevelEnumAccess().getRule();
	}

	//terminal ID:
	//
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
