/*
* generated by Xtext
*/
package mddProject.concreteSyntax.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import mddProject.concreteSyntax.services.JDSLGrammarAccess;

public class JDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private JDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected mddProject.concreteSyntax.parser.antlr.internal.InternalJDSLParser createParser(XtextTokenStream stream) {
		return new mddProject.concreteSyntax.parser.antlr.internal.InternalJDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ContentModel";
	}
	
	public JDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(JDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
