/*
* generated by Xtext
*/
package mddProject.concreteSyntax.ui.contentassist;

import mddProject.concreteSyntax.ui.contentassist.AbstractJDSLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class JDSLProposalProvider extends AbstractJDSLProposalProvider {

}
