/*
* generated by Xtext
*/
package mddProject.concreteSyntax.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class JDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("mddProject/concreteSyntax/parser/antlr/internal/InternalJDSL.tokens");
	}
}
