/*
 * generated by Xtext
 */
package mddProject.concreteSyntax;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JDSLRuntimeModule extends mddProject.concreteSyntax.AbstractJDSLRuntimeModule {

}
