/*
 * generated by Xtext
 */
package mddProject.concreteSyntax.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import mddProject.concreteSyntax.ui.internal.JDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return JDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return JDSLActivator.getInstance().getInjector(JDSLActivator.MDDPROJECT_CONCRETESYNTAX_JDSL);
	}
	
}
