/*
* generated by Xtext
*/
package mddProject.concreteSyntax.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class JDSLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
